/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => QuotePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var QuotePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "insert-quote",
      name: "Insert Quote",
      callback: () => {
        console.log("It worked!");
      }
    });
  }
  async onunload() {
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IHsgUGx1Z2luIH0gZnJvbSBcIm9ic2lkaWFuXCI7XG5cbmNvbnN0IHF1b3RlV2Vic2l0ZUFQSSA9IFwiaHR0cHM6Ly9hcGkucXVvdGFibGUuaW9cIjtcblxuZXhwb3J0IGRlZmF1bHQgY2xhc3MgUXVvdGVQbHVnaW4gZXh0ZW5kcyBQbHVnaW4ge1xuICBhc3luYyBvbmxvYWQoKSB7XG4gICAgLy8gQ29uZmlndXJlIHJlc291cmNlcyBuZWVkZWQgYnkgdGhlIHBsdWdpbi5cbiAgICB0aGlzLmFkZENvbW1hbmQoe1xuICAgICAgaWQ6IFwiaW5zZXJ0LXF1b3RlXCIsXG4gICAgICBuYW1lOiBcIkluc2VydCBRdW90ZVwiLFxuICAgICAgY2FsbGJhY2s6ICgpID0+IHtcbiAgICAgICAgY29uc29sZS5sb2coXCJJdCB3b3JrZWQhXCIpO1xuICAgICAgfSxcbiAgICB9KTtcbiAgfVxuICBhc3luYyBvbnVubG9hZCgpIHtcbiAgICAvLyBSZWxlYXNlIGFueSByZXNvdXJjZXMgY29uZmlndXJlZCBieSB0aGUgcGx1Z2luLlxuICB9XG59Il0sCiAgIm1hcHBpbmdzIjogIjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBLHNCQUF1QjtBQUl2QixJQUFxQixjQUFyQixjQUF5Qyx1QkFBTztBQUFBLEVBQzlDLE1BQU0sU0FBUztBQUViLFNBQUssV0FBVztBQUFBLE1BQ2QsSUFBSTtBQUFBLE1BQ0osTUFBTTtBQUFBLE1BQ04sVUFBVSxNQUFNO0FBQ2QsZ0JBQVEsSUFBSSxZQUFZO0FBQUEsTUFDMUI7QUFBQSxJQUNGLENBQUM7QUFBQSxFQUNIO0FBQUEsRUFDQSxNQUFNLFdBQVc7QUFBQSxFQUVqQjtBQUNGOyIsCiAgIm5hbWVzIjogW10KfQo=
